# list of directories with problemsets, relative to root
problems:
  - problems/part-1-initial
  - problems/part-2-teleports
  - problems/part-3-clones
# directory with known to be best solutions, safe to be submitted manually
gold: solutions_gold
# directory with solutions to evaluate
evaluate: evaluate
# directory with all existing submissions
submission: submissions
# do we need to verify solutions
verify: false
# do we need to use gold solution if it's known to be better
best: false
